name: Deploy to Shopify

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
        
    - name: Install Shopify CLI
      run: |
        curl -s https://shopify.dev/install.sh | bash
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        
    - name: Deploy theme to Shopify
      run: shopify theme push --store="t0uds3-a2.myshopify.com" --password="${{ secrets.SHOPIFY_STORE_PASSWORD }}" --allow-live --force --json
      env:
        SHOPIFY_CLI_NO_ANALYTICS: 1