name: Deploy to Shopify

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
        
    - name: Install Shopify CLI
      run: |
        npm install -g @shopify/cli @shopify/theme
        
    - name: Deploy theme to Shopify
      run: |
        echo "Deploying to Shopify..."
        
        # Create .shopify-cli.yml config
        cat > .shopify-cli.yml << EOF
        store: t0uds3-a2.myshopify.com
        EOF
        
        # Deploy using token authentication
        shopify theme push --live --allow-live --force
      env:
        SHOPIFY_CLI_THEME_TOKEN: ${{ secrets.SHOPIFY_ACCESS_TOKEN }}
        SHOPIFY_FLAG_STORE: t0uds3-a2.myshopify.com