name: Deploy to Shopify

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
        
    - name: Install Shopify CLI
      run: |
        curl -L -o shopify-cli.tar.gz https://github.com/Shopify/cli/releases/latest/download/shopify-cli-linux-amd64.tar.gz
        tar -xzf shopify-cli.tar.gz
        sudo mv shopify /usr/local/bin/
        shopify version
        
    - name: Verify theme files exist
      run: |
        echo "Theme files in root:"
        ls -la
        echo ""
        echo "Assets folder:"
        ls -la assets/ || echo "No assets folder"
        echo ""
        echo "CSS files:"
        find . -name "*.css" -type f || echo "No CSS files found"
        
    - name: Deploy theme to Shopify
      run: |
        shopify theme push --store="t0uds3-a2.myshopify.com" --password="${{ secrets.SHOPIFY_STORE_PASSWORD }}" --allow-live --force --json
      env:
        SHOPIFY_CLI_NO_ANALYTICS: 1
        
    - name: Verify deployment
      run: |
        echo "Deployment completed"
        echo "Store: t0uds3-a2.myshopify.com"
        echo "Deploying to live theme"
        echo "Deployed from: root directory"
        echo ""
        echo "Key files that should be deployed:"
        echo "- assets/godspeed-clean.css"
        echo "- layout/theme.liquid"
        echo "- sections/header.liquid"
        
  test-deployment:
    runs-on: ubuntu-latest
    needs: deploy
    if: success()
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
        
    - name: Install dependencies
      run: npm ci
      
    - name: Install Playwright
      run: npx playwright install --with-deps chromium
      
    - name: Test deployed site
      run: npx playwright test tests/visual-check.spec.ts --project=chromium
      env:
        SHOPIFY_STORE_URL: https://t0uds3-a2.myshopify.com
        SHOPIFY_STORE_PASSWORD: ${{ secrets.SHOPIFY_STORE_PASSWORD }}
        
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: deployment-test-results
        path: test-results/
